namespace MAUSIC.Data.Constants;

public static class RecommendationConstants
{
    public const int RecommendationThreshold = 2;

    public const int RecommendationCount = 2;

    public const float DefaultWeight = 0.5f;

    public const float AutoGeneratedWeight = 0.1f;

    public const float UserLiked = 0.4f;

    public const float UserDisliked = -0.4f;

    public const float UserFullyListened = 0.01f;

    public const float UserSkipped = -0.01f;
}